<div class="container">
    <table class="w-100">
        <div class="row text-center">
            <thead class="text-center">
                <tr>
                    <th>Jméno</th>
                    <th>Nejvyšší Vyznamenání</th>
                    <th>Medaile/Stužka</th>
                </tr>
            </thead>
        </div>
        <tbody class="text-center">
<?php  foreach ($clenove as $clen) { ?>
            <tr>
                <td><?= $clen["jmeno"] ?></td>
                <td><?= $clen["vyznamenani"] ?></td>  
                <td><?= $clen["stuzka"] ?></td>
            </tr>
<?php  } ?>
        </tbody>
    </table>
</div>