<div class="container mb-5">
    <div class="row">
        <p class="text-center">Seznam členů – Dotace z města Rychvald k 26. 11. 2022</p>
        <h2 class="mt-2 text-center">0-21</h2>
        <?php foreach ($dotace1 as $mlady) { ?>
            <div class="text-center">
                <p><?= $mlady["jmeno"] ?></p>
            </div>
        <?php } ?>
        <h2 class="mt-2 text-center">21+</h2>
        <?php foreach ($dotace2 as $dospely) { ?>
            <div class="text-center">
                <p><?= $dospely["jmeno"] ?></p>
            </div>
        <?php } ?>
        <h2 class="mt-2 text-center">Nesportovci</h2>
        <?php foreach ($nesport as $nesportovec) { ?>
            <div class="text-center">
                <p><?= $nesportovec["jmeno"] ?></p>
            </div>
        <?php } ?>
    </div>
</div>