<style>
    .dropdown {
        position: relative;
        display: inline-block;
    }
    .dropdown-menu1 {
        display: none;
        position: absolute;
        background-color: #f9f9f9;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        padding: 12px 16px;
        z-index: 1;
    }
    .dropdown:hover .dropdown-menu1 {
        display: block;
    }
    #menu2 {
        background-color: white;
        color: black;
        border: 2px solid #0d6efd;
    }
    #menu2:hover {
        background-color: #0d6efd;
        color: white
    }
</style>
<div class=" container">
    <div class=" dropdown row w-100 mb-2">
        <button class="btn btn-primary btn-lg btn-block w-100 dropdown-toggle menu2" type="button"  data-toggle="dropdown">2022</button>
        <ul class="dropdown-menu1 bg-secondary" role="menu" aria-labelledby="menu2">
            <div class="row"><a class="btn btn-secondary" href="https://zuzumalicka.rajce.idnes.cz/14.10.2022_-_Drakiada/" role="button">Drakiáda - 14.10.2022</a></div>
            <div class="row"><a class="btn btn-secondary" href="https://zuzumalicka.rajce.idnes.cz/11.9.2022_-_MLOK_Vrbice/" role="button">MLOK Vrbice - 11.9.2022</a></div>
            <div class="row"><a class="btn btn-secondary" href="https://zuzumalicka.rajce.idnes.cz/10.9.2022_-_MLOK_Horni_Sucha/" role="button">MLOK Horní Suchá - 10.9.2022</a></div>
            <div class="row"><a class="btn btn-secondary" href="https://zuzumalicka.rajce.idnes.cz/3.9.2022_-_MLOK_Rychvald/" role="button">MLOK Rychvald - 3.9.2022</a></div>
            <div class="row"><a class="btn btn-secondary" href="https://zuzumalicka.rajce.idnes.cz/13.8.2022_-_soutez_Petrvald/" role="button">soutěž Petřvald - 13.8.2022</a></div>
            <div class="row"><a class="btn btn-secondary" href="https://zuzumalicka.rajce.idnes.cz/12.6.2022_-_Krajske_kolo_dorostu/" role="button">Krajské kolo dorostu, Frýdek - Místek - 12.6.2022</a></div>
            <div class="row"><a class="btn btn-secondary" href="https://zuzumalicka.rajce.idnes.cz/15.5.2022_-_Okresni_kolo_dorostu_-_Cesky_Tesin/" role="button">Okresní kolo dorostu, Český Těšín - 15.5.2022</a></div>
            <div class="row"><a class="btn btn-secondary" href="https://zuzumalicka.rajce.idnes.cz/14.5.2022_-_Okresni_kolo_Plamen%2C_Cesky_Tesin/" role="button">Okresní kolo PLAMEN, Český Těšín - 14.5.2022</a></div>
            <div class="row"><a class="btn btn-secondary" href="https://zuzumalicka.rajce.idnes.cz/13.5.2022_-_OSMU/" role="button">OŠMÚ - 13.5.2022</a></div>
            <div class="row"><a class="btn btn-secondary" href="https://zuzumalicka.rajce.idnes.cz/7.5.2022_-_MLOK_Orlova_Mesto/" role="button">MLOK Orlová Město - 7.5.2022</a></div>
            <div class="row"><a class="btn btn-secondary" href="https://zuzumalicka.rajce.idnes.cz/9.4.2022_-_Okrskovy_turnaj_ve_stolnim_tenise/" role="button">Okrskový turnaj ve stolním tenise - 9.4.2022</a></div>
        </ul>
    </div>
    <div class="dropdown row w-100 mb-2">
        <button class="btn btn-primary btn-lg btn-block w-100 dropdown-toggle menu2" type="button"  data-toggle="dropdown">2021</button>
        <ul class="dropdown-menu1 bg-secondary" role="menu" aria-labelledby="menu2">

        </ul>
    </div>
    <div class="dropdown row w-100 mb-2">
        <button class="btn btn-primary btn-lg btn-block w-100 dropdown-toggle menu2" type="button"  data-toggle="dropdown">2020</button>
        <ul class="dropdown-menu1 bg-secondary" role="menu" aria-labelledby="menu2">

        </ul>
    </div>
    <div class="dropdown row w-100 mb-2">
        <button class="btn btn-primary btn-lg btn-block w-100 dropdown-toggle menu2" type="button"  data-toggle="dropdown">2019</button>
        <ul class="dropdown-menu1 bg-secondary" role="menu" aria-labelledby="menu2">

        </ul>
    </div>
    <div class="dropdown row w-100 mb-2">
        <button class="btn btn-primary btn-lg btn-block w-100 dropdown-toggle menu2" type="button"  data-toggle="dropdown">2018</button>
        <ul class="dropdown-menu1 bg-secondary" role="menu" aria-labelledby="menu2">

        </ul>
    </div>
    <div class="dropdown row w-100 mb-2">
        <button class="btn btn-primary btn-lg btn-block w-100 dropdown-toggle menu2" type="button"  data-toggle="dropdown">2017</button>
        <ul class="dropdown-menu1 bg-secondary" role="menu" aria-labelledby="menu2">

        </ul>
    </div>
    <div class="dropdown row w-100 mb-2">
        <button class="btn btn-primary btn-lg btn-block w-100 dropdown-toggle menu2" type="button"  data-toggle="dropdown">2016</button>
        <ul class="dropdown-menu1 bg-secondary" role="menu" aria-labelledby="menu2">

        </ul>
    </div>
    <div class="dropdown row w-100 mb-2">
        <button class="btn btn-primary btn-lg btn-block w-100 dropdown-toggle menu2" type="button"  data-toggle="dropdown">2015</button>
        <ul class="dropdown-menu1 bg-secondary" role="menu" aria-labelledby="menu2">

        </ul>
    </div>
    <div class="dropdown row w-100 mb-2">
        <button class="btn btn-primary btn-lg btn-block w-100 dropdown-toggle menu2" type="button"  data-toggle="dropdown">2014</button>
        <ul class="dropdown-menu1 bg-secondary" role="menu" aria-labelledby="menu2">

        </ul>
    </div>
    <div class="dropdown row w-100 mb-2">
        <button class="btn btn-primary btn-lg btn-block w-100 dropdown-toggle menu2" type="button"  data-toggle="dropdown">2013</button>
        <ul class="dropdown-menu1 bg-secondary" role="menu" aria-labelledby="menu2">

        </ul>
    </div>
    <div class="dropdown row w-100 mb-2">
        <button class="btn btn-primary btn-lg btn-block w-100 dropdown-toggle menu2" type="button"  data-toggle="dropdown">2012</button>
        <ul class="dropdown-menu1 bg-secondary" role="menu" aria-labelledby="menu2">

        </ul>
    </div>
    <div class="dropdown row w-100 mb-2">
        <button class="btn btn-primary btn-lg btn-block w-100 dropdown-toggle menu2" type="button"  data-toggle="dropdown">2011</button>
        <ul class="dropdown-menu1 bg-secondary" role="menu" aria-labelledby="menu2">

        </ul>
    </div>
    <div class="dropdown row w-100 mb-2">
        <button class="btn btn-primary btn-lg btn-block w-100 dropdown-toggle menu2" type="button"  data-toggle="dropdown">2010</button>
        <ul class="dropdown-menu1 bg-secondary" role="menu" aria-labelledby="menu2">

        </ul>
    </div>
    <div class="dropdown row w-100 mb-2">
        <button class="btn btn-primary btn-lg btn-block w-100 dropdown-toggle menu2" type="button"  data-toggle="dropdown">2009</button>
        <ul class="dropdown-menu1 bg-secondary" role="menu" aria-labelledby="menu2">

        </ul>
    </div>
</div>