<div class="container mb-5">
    <div class="row">
        <h3>Několik slov z historie.</h3>
    </div>
    <div class="row text-justify">
        <p><b>Z historických materiálů čteme:</b> Rychvaldský Dobrovolný sbor hasičský byl u nás ve Slezsku založen v roce 1895 jako osmý český sbor a roku následujícího byly založeny sbory v Morávce a v Kunčicích nad Ostravicí. Po celý rok 1894 trvaly přípravy pro založení hasičského sboru českého v Rychvaldě a bylo tu třeba překonati mnoho potíží a nepřátelských útoků, než se myšlenka ta dne 17. března 1895 uskutečnila zásluhou jednatele župy J Tomáška, který vůbec zúčastnil se účinně zakládání všech sborů zřízených v době jeho činnosti. Z místních činitel zasloužili se o zřízení sboru Ant. Brak, František. Šmuk, Richard Ševčík, Ad. Musiol a mnozí jiní.</p>
    </div>
    <div class="row text-justify">
        <p>16. července 1905 oslavil hasičský sbor v Rychvaldě své desetileté trvání a šestisetletou památku prvé zmínky obce Rychvaldu v dějinách. Kdo ohrožené národnostní poměry obce Rychvaldu v době před rokem 1905 i pozdější zná, musí toto jubileum sboru, jako předního pracovníka rychvaldského označiti velmi významným. Na tom i předcházejícím sjezdu župním projednány byly veškeré naléhavé záležitosti organizačního a technického rázu sdružených sborů a oceněna náležitě neúnavná obětavost hasičského sboru v Rychvaldě, jakož i jeho činovníků, kteří svou vytrvalou prací jedině přispěli k zachování českosti obce Rychvaldu.</p>
    </div>
    <div class="row">
        <div class="text-center">
            <img src="galery/Rychvald_history_01.jpg" alt="" width="300" height="auto">
        </div>
    </div>
    <div class="row text-justify">
        <p>17. března 1895 byl podle zakládajícího protokolu založen Dobrovolný sbor hasičský v Rychvaldě. Jeho prvním voleným starostou byl pan Anton Brak a jednatelem byl zvolen pan Richard Ševčík.</p>
    </div>
    <div class="row text-justify">
        <p>Začala se psát historie dobrovolného hasičstva v Rychvaldě. Začala neúnavná a obětavá práce dobrovolných hasičů, kteří, jak už bylo řečeno, obětovali svůj volný čas pomoci a ochraně svých bližních pří ochraně jejich životů a majetků. A nebyl to jen jejich volný čas. Vybudování postupně několika hasičských zbrojnic a jejich vybavení tak, aby se dalo bojovat s požáry si vyžádalo nemalé finanční prostředky, které se v té době daly získat většinou pouze ze sbírek od občanů. Tyto velmi těžké podmínky však nevzaly chut‘ do práce našim předchůdcům a jejich výsledky byly brzy skutečně obdivuhodné.</p>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-auto">
                <img src="galery/Rychvald_history_02.jpg" alt="" width="208" height="300">
            </div>
            <div class="col-lg">
                <p>Dobrovolný hasičský sbor se tak velmi brzy stal organizací, která v tehdejší obci Rychvald začala Ovlivňovat veškerou činnost a stát se jejím členem si považovalo za čest mnoho rychvaldských občanů. Bohužel vždy tornu tak nebylo. Přicházely také problémy, které byly</p>
                <p>v mnoha případech ovlivněny různými změnami ve vedení obce a v politických událostech.</p>
                <p>Popsat podrobně historii sboru, který si dnes připomíná své 110. výročí v tak malé brožůrce není dost dobře možné. Je však naši snahou si připomenout alespoň některé důležité události ze života rychvaldských dobrovolných hasičů.</p>
                <p>První polovina historie našeho sboru byla provázena především výstavbami hasičských zbrojíren v různých částech Rychvaldu. Bylo tornu tak proto, že tehdejší hasičská technika byla dopravována k požárům koňskými potahy a tak doba dojezdu k zásahu byla podstatně delší než dnes. Proto byla například 1. Hasičská zbrojírna vybudována v Rychvaldě na Podlesí, II. Hasičská zbrojírna</p>
                <p>v Rychvaldě na Fojtství, vždy co nejblíže nejvíce zastavěným oblastem. Následovaly další Zbrojírny např. „u Šmuků“, IV. Hasičská zbrojírna u Laštůvků atd.</p>
            </div>
        </div>
    </div>
    <div class="row text-justify">
        <p>Hasičské zbrojírny v té době sloužily svému účelu velmi dobře. Udržování zbrojíren a tehdejší hasičské techniky bylo mnohem náročnější než dnes. Přesto ji naši předchůdci věnovali všechen svůj volný čas. Dobře věděli, že v případě požáru jsou odkázáni sami na sebe a někdy na pomoc sousedních dobrovolných hasičů. Profesionální hasiči v té době neexistovali.</p>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-auto">
                <img src="galery/Rychvald_history_03.jpg" alt="">
            </div>
            <div class="col-lg">
                <p>Přelomem v historii Dobrovolných hasičů v Rychvaldě byl rok 1945. Staré Hasičské zbrojírny dosloužily. Po II. světové válce zůstala hasičská technika a vybavení, se kterým se nedalo u požárů zasahovat a dobrovolní hasiči stáli před problémem, co dál. S tehdejším vedením obce se pustili do odvážného díla. Z finanční sbírky od občanů a příspěvkem od obce se pustili svépomocně do výstavby tehdejšího Požárního domu.</p>
                <p>Začalo nové nadšení do další práce. V roce 1953 byl Požární dům zkolaudován a postupně vybaven požární technikou. Organizace se začala znovu rozvíjet. Dobrovolní hasiči z Rychvaldu se vrátili ke svým tradicím a začali získávat dobré jméno nejen v obci, ale</p>
                <p>i v celém okrese Karviná. Členové sboru se zapojili také do práce v okrsku a v okresním výboru. Sbor si začal vychovávat své nové členy</p>
            </div>
        </div>
    </div>
    <div class="row text-justify">
        <p>v řadách mladých hasičů. Výsledky obětavé práce velké většiny členů a funkcionářů dobrovolných hasičů získávaly uznání nejen v rámci Rychvaldu, ale i v rámci okresu a kraje.</p>
    </div>
    <div class="row">
        <div class="text-center">
            <img src="galery/Rychvald_history_04.jpg" alt="" width="300" height="auto">
        </div>
    </div>
    <div class="row text-justify">
        <p>Bohužel i tehdy nešlo všechno snadno a nastaly problémy, které podstatně činnost dobrovolných hasičů v Rychvaldě narušovaly. Jednalo se o zabírání prostorů Požárního domu tehdejším vedením města k jiným účelům a to tak, že v něm pro hasiče nezůstalo skoro žádné místo. Problém nastal i s dosluhující technikou tak, že nebylo u požárů čím zasahovat. Nastala dlouhá jednání mezi tehdejším vedením Rychvaldu a hasiči, které jsme po dlouhém vytrvalém boji vyhráli. Začínali jsme znovu a svou obětavou prací jsme se vrátili k výsledkům, kterých jsme nakonec dosáhli.</p>
    </div>
    <div class="row text-justify">
        <p>Dnes můžeme s hrdostí říci, že dobrovolní hasiči v Rychvaldě pokračují v dobrých tradicích svých předchůdců nadále a jsou připraveni pomáhat svým spoluobčanům při ochraně jejich životů a majetku.</p>
    </div>
</div>