<div class="container mt-2 mb-5">
    <div class="row text-center text-primary">
        <h2>Sdružení hasičů Čech, Moravy a Slezska</h2>
    </div>
    <div class="row text-center text-primary">
        <h2>Sbor dobrovolných hasičů Rychvald</h2>
    </div>
    <div class="text-center text-secondary">
        <h3>ul. Orlovská čp. 1221</h3>
        <h3>735 32 Rychvald</h3>
        <div class="row embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d737.4750266389859!2d18.37861622122536!3d49.86599074959458!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4713fd79f9504f51%3A0x4c6c97b1f711f7c4!2sSDH%20Rychvald!5e0!3m2!1scs!2spt!4v1675784173279!5m2!1scs!2spt" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
    </div>
</div>