<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="bootstrap/bootstrap.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="bootstrap/bootstrap.bundle.js"></script>
    <title>SDH Rychvald</title>
    <style>
        .nadpis {
            min-width: 200px
        }
        @media screen and (min-width: 1400px) {
            .dropdown {
                position: relative;
                display: inline-block;
            }
            .dropdown-menu {
                display: none;
                position: absolute;
                background-color: #f9f9f9;
                min-width: 0px;
                box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
                padding: 12px 16px;
                z-index: 2;
            }
            .dropdown:hover .dropdown-menu {
                display: block;
            }
            .burger-toggle {
                display: none;
            }
            .show {
                display: block !important;
            }
        }
        @media screen and (max-width: 1400px) {
            .burger-toggle {
                display: block;
            }
            .burger-dropdown {
                display: none;
            }
            .show {
                display: block !important;
            }
            .burger {
                position: relative;
                display: inline-block;
            }
            .burger-dropdown {
                display: none;
                position: absolute;
                background-color: #dc3545 !important;
                min-width: 0px;
                box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
                padding: 12px 16px;
                z-index: 2;
            }
            .dropdown {
                width: 100%;
            }
            .btn-uvod {
                width: 100%;
            }
            .dropdown-menu {
                width: 100%;
                position: relative;
            }
            .dropdown-menu {
                display: none;
                position: relative;
                min-width: 0px;
                box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
                padding: 12px 16px;
                z-index: 1;
            }
            .dropdown {
                position: relative;
                display: inline-block;
            }
        }
    </style>
    <script>
        function myFunction(id) {
            document.getElementById(id).classList.toggle("show");
        }
    </script>
</head>
<body>
    <header class="bg-secondary">
        <div class="container pt-2">
            <div class="row">
                <div class="col text-center nadpis">
                    <h1 class="text-danger"><a href="index.php" class="navbar-brand">SDH Rychvald</a></h1>
                </div>
                <div class="col nadpis">
                    <nav class="navbar">
                        <span class="burger w-100">
                            <button onclick="myFunction('burger-toggle')" class="btn btn-danger w-100 burger-toggle">Menu</button>
                            <ul class="burger-dropdown w-100 bg-secondary" id="burger-toggle">
                                <a href="index.php" class="btn btn-danger btn-uvod">Úvod</a>
                                <span class="dropdown">
                                    <button onclick="myFunction('aktuality')" class="btn btn-danger dropdown-toggle w-100">Aktuality</button>
                                    <ul class="dropdown-menu bg-danger" id="aktuality">
                                        <div class="row"><a href="novinky.php" class="btn btn-danger">Novinky</a></div>
                                        <div class="row"><a href="clanky.php" class="btn btn-danger">Články</a></div>
                                        <div class="row"><a href="gallery.php" class="btn btn-danger">Fotogalerie</a></div>
                                        <div class="row"><a href="prevence.php" class="btn btn-danger">Prevence</a></div>
                                    </ul>
                                </span>
                                <span class="dropdown">
                                    <button onclick="myFunction('JSDH')" class="btn btn-danger dropdown-toggle w-100">JSDH</button>
                                    <ul class="dropdown-menu bg-danger" id="JSDH">
                                        <div class="row"><a href="technicke_prostredky.php" class="btn btn-danger">Naše technické prostředky</a></div>
                                        <div class="row"><a href="vyjezdova_jednotka.php" class="btn btn-danger">Výjezdová jednotka</a></div>
                                        <div class="row"><a href="vyjezdy.php" class="btn btn-danger">Výjezdy</a></div>
                                    </ul>
                                </span>
                                <span class="dropdown">
                                    <button onclick="myFunction('SDH')" class="btn btn-danger dropdown-toggle w-100">SDH Rychvald</button>
                                    <ul class="dropdown-menu bg-danger" id="SDH">
                                        <div class="row"><a href="vybor.php" class="btn btn-danger">Výbor</a></div>
                                        <div class="row"><a href="history.php" class="btn btn-danger">Historie</a></div>
                                        <div class="row"><a href="clenove.php" class="btn btn-danger">Členové</a></div>
                                        <div class="row"><a href="druzebni_spoluprace.php" class="btn btn-danger">Družební spolupráce</a></div>
                                        <div class="row"><a href="dotace.php" class="btn btn-danger">dotace</a></div>
                                    </ul>
                                </span>
                                <span class="dropdown">
                                    <button onclick="myFunction('PS')" class="btn btn-danger dropdown-toggle w-100">Požární sport</button>
                                    <ul class="dropdown-menu bg-danger" id="PS">
                                        <div class="row"><a href="mladi_hasici.php" class="btn btn-danger">Mladí hasiči</a></div>
                                        <div class="row"><a href="souteze.php" class="btn btn-danger">Soutěže</a></div>
                                        <div class="row"><a href="partneri.php" class="btn btn-danger">Partneři</a></div>
                                    </ul>
                                </span>
                            </ul>
                        </span>
                    </nav>
                </div>
            </div>
        </div>
    </header>