<div class="container">
    <div class="row text-center">
        <h2>Partneři</h2>
        <p class="mt-5">I v letošním roce děkujeme Moravskoslezskému kraji za poskytnutí dotací na podporu našeho sboru. Sbor dobrovolných hasičů Rychvald obdržel dotaci Moravskoslezského kraje z titulu "Dotační program na podporu sborů dobrovolných hasičů v roce 2020". Dotace byla použita na nákup vybavení pro naše mladé hasiče a to kladiny pro požární sport a také na pořízení plechové garáže, ve které se toto vybavení pro požární sport bude uskladňovat. V roce 2020 připravil Moravskoslezský kraj dotační titul zaměřený právě na podporu činnosti sboru dobrovolných hasičů v našem kraji. Díky této dotaci máme možnost kvalitně a bezpečně uskladnit nejen nově pořízené vybavení, ale je zde dostatek místa i pro vybavení, které jsme pořídili již z minulých dotací.</p>
    </div>
    <div class="row">
        <div class="text-center">
            <a href="https://www.msk.cz"><img src="galery/Rychvald_msk_logo.jpg" alt="" width="300" height="auto"></a>
        </div>
    </div>
    <div class="row text-center">
        <p>Z poskytnutých dotací jsme zakoupili tyto věci.</p>
    </div>
    <div class="row text-center">
        <div class="col">
            <img src="galery/Rychvald_partner_01.jpg" alt="" width="300" height="auto">
        </div>
        <div class="col">
            <img src="galery/Rychvald_partner_02.jpg" alt="" width="300" height="auto">
        </div>
    </div>
    <div class="row text-center mt-5">
        <p>Děkujeme Moravskoslezskému kraji za poskytnutí dotací na podporu našeho sboru. Sbor dobrovolných hasičů Rychvald obdržel dotaci Moravskoslezského kraje z titulu "Program na podporu dobrovolných hasičů v roce 2019". Dotace byla použita na nákup vybavení, které je používáno při výcviku a práci s našimi mladými hasiči a při pořádání soutěžních akcí. V roce 2019 připravil Moravskoslezský kraj dotační titul zaměřený právě na podporu činnosti sboru dobrovolných hasičů v našem kraji. Pořádání každé soutěže, či práce s našimi mladými hasiči vyžaduje nejen spoustu času, ale také kvalitní a moderní vybavení, které jsme si díky Moravskoslezskému kraji mohli ze získané dotace pořídit.</p>
    </div>
    <div class="row">
        <div class="text-center">
            <a href="https://www.msk.cz"><img src="galery/Rychvald_msk_logo.jpg" alt="" width="300" height="auto"></a>
        </div>
    </div>
    <div class="row text-center">
        <p>Z poskytnutých dotací jsme zakoupili tyto věci.</p>
    </div>
    <div class="row text-center">
        <div class="col">
            <img src="galery/Rychvald_partner_03.jpg" alt="" width="300" height="auto">
        </div>
        <div class="col">
            <img src="galery/Rychvald_partner_04.jpg" alt="" width="300" height="auto">
        </div>
    </div>
    <div class="row text-center">
        <div class="col">
            <img src="galery/Rychvald_partner_05.jpg" alt="" width="300" height="auto">
        </div>
        <div class="col">
            <img src="galery/Rychvald_partner_06.jpg" alt="" width="300" height="auto">
        </div>
    </div>
</div>