<div class="container mt-2 mb-5">
<h2 class="text-center">2022</h2>
    <?php foreach ($v2022 as $vyjezd) { ?>
        <div class="row text-center">
            <div class="col">
                <p><?= $vyjezd["datum"] ?></p>
            </div>
            <div class="col">
                <p><?= $vyjezd["typ"] ?></p>
            </div>
            <div class="col">
                <p><?= $vyjezd["technika"] ?></p>
            </div>
        </div>
    <?php } ?>
    <h2 class="text-center">2021</h2>
    <?php foreach ($v2021 as $vyjezd) { ?>
        <div class="row text-center">
            <div class="col">
                <p><?= $vyjezd["datum"] ?></p>
            </div>
            <div class="col">
                <p><?= $vyjezd["typ"] ?></p>
            </div>
            <div class="col">
                <p><?= $vyjezd["technika"] ?></p>
            </div>
        </div>
    <?php } ?>
    <h2 class="text-center">2020</h2>
    <?php foreach ($v2020 as $vyjezd) { ?>
        <div class="row text-center">
            <div class="col">
                <p><?= $vyjezd["datum"] ?></p>
            </div>
            <div class="col">
                <p><?= $vyjezd["typ"] ?></p>
            </div>
            <div class="col">
                <p><?= $vyjezd["technika"] ?></p>
            </div>
        </div>
    <?php } ?>
    <h2 class="text-center">2019</h2>
    <?php foreach ($v2019 as $vyjezd) { ?>
        <div class="row text-center">
            <div class="col">
                <p><?= $vyjezd["datum"] ?></p>
            </div>
            <div class="col">
                <p><?= $vyjezd["typ"] ?></p>
            </div>
            <div class="col">
                <p><?= $vyjezd["technika"] ?></p>
            </div>
        </div>
    <?php } ?>
    <h2 class="text-center">2018</h2>
    <?php foreach ($v2018 as $vyjezd) { ?>
        <div class="row text-center">
            <div class="col">
                <p><?= $vyjezd["datum"] ?></p>
            </div>
            <div class="col">
                <p><?= $vyjezd["typ"] ?></p>
            </div>
            <div class="col">
                <p><?= $vyjezd["technika"] ?></p>
            </div>
        </div>
    <?php } ?>
    <h2 class="text-center">2017</h2>
    <?php foreach ($v2017 as $vyjezd) { ?>
        <div class="row text-center">
            <div class="col">
                <p><?= $vyjezd["datum"] ?></p>
            </div>
            <div class="col">
                <p><?= $vyjezd["typ"] ?></p>
            </div>
            <div class="col">
                <p><?= $vyjezd["technika"] ?></p>
            </div>
        </div>
    <?php } ?>
    <h2 class="text-center">2016</h2>
    <?php foreach ($v2016 as $vyjezd) { ?>
        <div class="row text-center">
            <div class="col">
                <p><?= $vyjezd["datum"] ?></p>
            </div>
            <div class="col">
                <p><?= $vyjezd["typ"] ?></p>
            </div>
            <div class="col">
                <p><?= $vyjezd["technika"] ?></p>
            </div>
        </div>
    <?php } ?>
    <h2 class="text-center">2015</h2>
    <?php foreach ($v2015 as $vyjezd) { ?>
        <div class="row text-center">
            <div class="col">
                <p><?= $vyjezd["datum"] ?></p>
            </div>
            <div class="col">
                <p><?= $vyjezd["typ"] ?></p>
            </div>
            <div class="col">
                <p><?= $vyjezd["technika"] ?></p>
            </div>
        </div>
    <?php } ?>
    <h2 class="text-center">2014</h2>
    <?php foreach ($v2014 as $vyjezd) { ?>
        <div class="row text-center">
            <div class="col">
                <p><?= $vyjezd["datum"] ?></p>
            </div>
            <div class="col">
                <p><?= $vyjezd["typ"] ?></p>
            </div>
            <div class="col">
                <p><?= $vyjezd["technika"] ?></p>
            </div>
        </div>
    <?php } ?>
</div>