<div class="container">
    <div class="row text-center">
        <p>Jednotka se schází každou sudou neděli od 8:00.</p>
        <h2>VÝJEZDOVÁ JEDNOTKA</h2>
    </div>
    <div class="row text-center">
        <p>Velitel: Kohl Jakub</p>
    </div>
    <div class="row text-center">
        <p>Beňovič Igor</p>
    </div>
    <div class="row text-center">
        <p>Budník René</p>
    </div>
    <div class="row text-center">
        <p>Dunajčíková Zuzana</p>
    </div>
    <div class="row text-center">
        <p>Fišer Martin Dis</p>
    </div>
    <div class="row text-center">
        <p>Foltyn Evžen</p>
    </div>
    <div class="row text-center">
        <p>Helis František</p>
    </div>
    <div class="row text-center">
        <p>Helis Rudolf</p>
    </div>
    <div class="row text-center">
        <p>Jankovič Vlastimil</p>
    </div>
    <div class="row text-center">
        <p>Korhel Petr</p>
    </div>
    <div class="row text-center">
        <p>Orel Michal</p>
    </div>
    <div class="row text-center">
        <p>Pácal Jakub</p>
    </div>
    <div class="row text-center">
        <p>Stašák Jakub</p>
    </div>
    <div class="row text-center">
        <p>Stuchlý Radek</p>
    </div>
    <div class="row text-center">
        <p>Tarnawa Jakub</p>
    </div>
    <div class="row text-center">
        <p>Zajíc Petr</p>
    </div>
    <div class="row text-center">
        <p>Zajíc Zdeněk</p>
    </div>
    <div class="row">
        <img src="galery/Rychvald_vyj_01.jpg" alt="" class="col-4">
        <img src="galery/Rychvald_vyj_02.jpg" alt="" class="col-4">
        <img src="galery/Rychvald_vyj_03.jpg" alt="" class="col-4">
    </div>
</div>